
LiveNodeList {
  '0':
   Element {
     _nsMap: {},
     attributes: { _ownerElement: [Circular] },
     childNodes: { '0': [Text], length: 1 },
     ownerDocument:
      Document {
        implementation: [Object],
        childNodes: [Object],
        doctype: null,
        documentURI: undefined,
        documentElement: [Element],
        firstChild: [Element],
        lastChild: [Element],
        _inc: 14 },
     nodeName: 'child',
     tagName: 'child',
     namespaceURI: 'a',
     localName: 'child',
     parentNode:
      Element {
        _nsMap: [Object],
        attributes: [Object],
        childNodes: [Object],
        ownerDocument: [Document],
        nodeName: 'xml',
        tagName: 'xml',
        namespaceURI: 'a',
        localName: 'xml',
        previousSibling: null,
        nextSibling: null,
        parentNode: [Document],
        lineNumber: 1,
        columnNumber: 1,
        firstChild: [Text],
        lastChild: [Text] },
     previousSibling:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Element],
        previousSibling: null,
        nextSibling: [Circular],
        lineNumber: 1,
        columnNumber: 33 },
     nextSibling:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Element],
        previousSibling: [Circular],
        nextSibling: [Element],
        lineNumber: 2,
        columnNumber: 21 },
     lineNumber: 2,
     columnNumber: 2,
     firstChild:
      Text {
        ownerDocument: [Document],
        data: 'test',
        nodeValue: 'test',
        length: 4,
        parentNode: [Circular],
        previousSibling: null,
        nextSibling: null,
        lineNumber: 2,
        columnNumber: 9 },
     lastChild:
      Text {
        ownerDocument: [Document],
        data: 'test',
        nodeValue: 'test',
        length: 4,
        parentNode: [Circular],
        previousSibling: null,
        nextSibling: null,
        lineNumber: 2,
        columnNumber: 9 } },
  '1':
   Element {
     _nsMap: {},
     attributes: { _ownerElement: [Circular] },
     childNodes: {},
     ownerDocument:
      Document {
        implementation: [Object],
        childNodes: [Object],
        doctype: null,
        documentURI: undefined,
        documentElement: [Element],
        firstChild: [Element],
        lastChild: [Element],
        _inc: 14 },
     nodeName: 'child',
     tagName: 'child',
     namespaceURI: 'a',
     localName: 'child',
     parentNode:
      Element {
        _nsMap: [Object],
        attributes: [Object],
        childNodes: [Object],
        ownerDocument: [Document],
        nodeName: 'xml',
        tagName: 'xml',
        namespaceURI: 'a',
        localName: 'xml',
        previousSibling: null,
        nextSibling: null,
        parentNode: [Document],
        lineNumber: 1,
        columnNumber: 1,
        firstChild: [Text],
        lastChild: [Text] },
     previousSibling:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Element],
        previousSibling: [Element],
        nextSibling: [Circular],
        lineNumber: 2,
        columnNumber: 21 },
     nextSibling:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Element],
        previousSibling: [Circular],
        nextSibling: [Element],
        lineNumber: 3,
        columnNumber: 17 },
     lineNumber: 3,
     columnNumber: 2 },
  '2':
   Element {
     _nsMap: {},
     attributes: { _ownerElement: [Circular] },
     childNodes: {},
     ownerDocument:
      Document {
        implementation: [Object],
        childNodes: [Object],
        doctype: null,
        documentURI: undefined,
        documentElement: [Element],
        firstChild: [Element],
        lastChild: [Element],
        _inc: 14 },
     nodeName: 'child',
     tagName: 'child',
     namespaceURI: 'a',
     localName: 'child',
     parentNode:
      Element {
        _nsMap: [Object],
        attributes: [Object],
        childNodes: [Object],
        ownerDocument: [Document],
        nodeName: 'xml',
        tagName: 'xml',
        namespaceURI: 'a',
        localName: 'xml',
        previousSibling: null,
        nextSibling: null,
        parentNode: [Document],
        lineNumber: 1,
        columnNumber: 1,
        firstChild: [Text],
        lastChild: [Text] },
     previousSibling:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Element],
        previousSibling: [Element],
        nextSibling: [Circular],
        lineNumber: 3,
        columnNumber: 17 },
     nextSibling:
      Text {
        ownerDocument: [Document],
        data: '\n',
        nodeValue: '\n',
        length: 1,
        parentNode: [Element],
        previousSibling: [Circular],
        nextSibling: null,
        lineNumber: 4,
        columnNumber: 10 },
     lineNumber: 4,
     columnNumber: 2 },
  _node:
   Element {
     _nsMap: { '': 'a', c: './lite' },
     attributes:
      { '0': [Attr],
        '1': [Attr],
        '2': [Attr],
        '3': [Attr],
        _ownerElement: [Circular],
        length: 4 },
     childNodes:
      { '0': [Text],
        '1': [Element],
        '2': [Text],
        '3': [Element],
        '4': [Text],
        '5': [Element],
        '6': [Text],
        length: 7 },
     ownerDocument:
      Document {
        implementation: [Object],
        childNodes: [Object],
        doctype: null,
        documentURI: undefined,
        documentElement: [Circular],
        firstChild: [Circular],
        lastChild: [Circular],
        _inc: 14 },
     nodeName: 'xml',
     tagName: 'xml',
     namespaceURI: 'a',
     localName: 'xml',
     previousSibling: null,
     nextSibling: null,
     parentNode:
      Document {
        implementation: [Object],
        childNodes: [Object],
        doctype: null,
        documentURI: undefined,
        documentElement: [Circular],
        firstChild: [Circular],
        lastChild: [Circular],
        _inc: 14 },
     lineNumber: 1,
     columnNumber: 1,
     firstChild:
      Text {
        ownerDocument: [Document],
        data: '\n\t',
        nodeValue: '\n\t',
        length: 2,
        parentNode: [Circular],
        previousSibling: null,
        nextSibling: [Element],
        lineNumber: 1,
        columnNumber: 33 },
     lastChild:
      Text {
        ownerDocument: [Document],
        data: '\n',
        nodeValue: '\n',
        length: 1,
        parentNode: [Circular],
        previousSibling: [Element],
        nextSibling: null,
        lineNumber: 4,
        columnNumber: 10 } },
  _refresh: [Function],
  '$$length': 3,
  _inc: 14 }
